# Generated by Django 5.0.1 on 2024-02-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
