# Generated by Django 5.0.1 on 2024-02-22 09:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('Comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('blogparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghome.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('commentparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghome.comment')),
            ],
        ),
    ]
