# Generated by Django 5.0.1 on 2024-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0004_alter_blog_content_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
