# Generated by Django 5.0.1 on 2024-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
