# Generated by Django 5.0.1 on 2024-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0006_comment_cid_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blogimages'),
        ),
    ]
